# -*- coding: utf-8 -*-
"""Proyecto biblioteca - Libris_v3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCCmA_XEyFYgz-EMIx9ah_CJN1z6ZGae
"""

import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
import streamlit as st

# Configuración de la página
st.set_page_config(page_title="Libris", page_icon="📚", layout="wide")

st.title("📚 Organizador y Analizador de Biblioteca")
st.markdown(
    "Carga tus libros, selecciona los criterios de ordenamiento y revisa las estadísticas de tu colección."
)

# --- BARRA LATERAL: CARGA DE DATOS ---
st.sidebar.header("1. Carga de Libros")
opcion_carga = st.sidebar.radio(
    "¿Cómo deseas cargar tus datos?",
    ("Plantilla de Ejemplo", "Subir CSV / Excel", "Carga Manual"),
)

df = None

if opcion_carga == "Plantilla de Ejemplo":
    datos_demo = [
        {
            "titulo": "Las Palmeras Salvajes",
            "autor": "Faulkner, William",
            "genero_autor": "Varón",
            "pais_autor": "EE.UU.",
            "genero_literario": "Ficción",
            "editorial": "Debolsillo",
            "anio_publicacion": 1939,
        },
        {
            "titulo": "Gente Normal",
            "autor": "Rooney, Sally",
            "genero_autor": "Mujer",
            "pais_autor": "Irlanda",
            "genero_literario": "Ficción",
            "editorial": "Random House",
            "anio_publicacion": 2018,
        },
        {
            "titulo": "El segundo sexo",
            "autor": "de Beauvoir, Simone",
            "genero_autor": "Mujer",
            "pais_autor": "Francia",
            "genero_literario": "Ensayo",
            "editorial": "Cátedra",
            "anio_publicacion": 1949,
        },
        {
            "titulo": "Cien años de soledad",
            "autor": "García Márquez, Gabriel",
            "genero_autor": "Varón",
            "pais_autor": "Colombia",
            "genero_literario": "Ficción",
            "editorial": "Sudamericana",
            "anio_publicacion": 1967,
        },
        {
            "titulo": "Ficciones",
            "autor": "Borges, Jorge Luis",
            "genero_autor": "Varón",
            "pais_autor": "Argentina",
            "genero_literario": "Ficción",
            "editorial": "Sur",
            "anio_publicacion": 1944,
        },
        {
            "titulo": "El invencible verano de Liliana",
            "autor": "Rivera Garza, Cristina",
            "genero_autor": "Mujer",
            "pais_autor": "México",
            "genero_literario": "No Ficción",
            "editorial": "Random House",
            "anio_publicacion": 2021,
        },
        {
            "titulo": "Sapiens",
            "autor": "Harari, Yuval Noah",
            "genero_autor": "Varón",
            "pais_autor": "Israel",
            "genero_literario": "Ensayo",
            "editorial": "Debate",
            "anio_publicacion": 2011,
        },
    ]
    df = pd.DataFrame(datos_demo)
    st.sidebar.success("✅ Plantilla cargada con éxito")

elif opcion_carga == "Subir CSV / Excel":
    archivo_subido = st.sidebar.file_uploader(
        "Sube tu archivo", type=["csv", "xlsx"]
    )
    if archivo_subido is not None:
        try:
            if archivo_subido.name.endswith(".csv"):
                df = pd.read_csv(archivo_subido)
            else:
                df = pd.read_excel(archivo_subido)
            st.sidebar.success("✅ Archivo cargado con éxito")
        except Exception as e:
            st.sidebar.error(f"Error al leer el archivo: {e}")

elif opcion_carga == "Carga Manual":
    st.sidebar.subheader("Agregar un libro")
    with st.sidebar.form("form_manual"):
        titulo = st.text_input("Título")
        autor = st.text_input("Autor (Apellido, Nombre)")
        genero_autor = st.selectbox(
            "Género del Autor/a", ["Mujer", "Varón", "No Binarie / Otro"]
        )
        pais_autor = st.text_input("País del Autor/a")
        genero_literario = st.text_input("Género Literario")
        editorial = st.text_input("Editorial")
        anio_publicacion = st.number_input(
            "Año de Publicación", min_value=0, max_value=2030, value=2000
        )

        btn_agregar = st.form_submit_button("Agregar Libro")
        if btn_agregar and titulo and autor:
            nuevo_libro = {
                "titulo": titulo,
                "autor": autor,
                "genero_autor": genero_autor,
                "pais_autor": pais_autor,
                "genero_literario": genero_literario,
                "editorial": editorial,
                "anio_publicacion": anio_publicacion,
            }
            if "libros_manuales" not in st.session_state:
                st.session_state["libros_manuales"] = []
            st.session_state["libros_manuales"].append(nuevo_libro)
            st.sidebar.success(f"¡'{titulo}' agregado!")

    if (
        "libros_manuales" in st.session_state
        and len(st.session_state["libros_manuales"]) > 0
    ):
        df = pd.DataFrame(st.session_state["libros_manuales"])

# --- PESTAÑAS PRINCIPALES ---
if df is not None and not df.empty:
    tab1, tab2, tab3 = st.tabs(
        ["📚 Orden Recomendado", "📊 Reporte Estadístico", "📄 Ver/Exportar Datos"]
    )

    # PESTAÑA 1: ORDENAMIENTO
    with tab1:
        st.subheader("Configura los Criterios de Orden")
        columnas_disponibles = list(df.columns)
        criterios_defecto = [
            c
            for c in ["genero_literario", "autor", "anio_publicacion"]
            if c in columnas_disponibles
        ]

        criterios = st.multiselect(
            "Selecciona el orden de prioridad para tus estantes:",
            options=columnas_disponibles,
            default=criterios_defecto,
        )

        if criterios:
            df_ordenado = df.sort_values(by=criterios)
            st.markdown("### 🏷️ Orden Sugerido para tu Estantería")
            st.dataframe(df_ordenado, use_container_width=True)

    # PESTAÑA 2: ESTADÍSTICAS
    with tab2:
        st.subheader("Estadísticas de tu Biblioteca")
        col1, col2 = st.columns(2)
        col1.metric("Total de Libros", len(df))
        col2.metric(
            "Autores Únicos", df["autor"].nunique() if "autor" in df else 0
        )

        # GÉNERO
        if "genero_autor" in df:
            st.markdown("---")
            st.markdown("#### Distribución por Género de Autores/as")
            fig1, ax1 = plt.subplots(figsize=(5, 4))
            df["genero_autor"].value_counts().plot(
                kind="pie", autopct="%1.1f%%", ax=ax1
            )
            ax1.set_ylabel("")
            st.pyplot(fig1)

        # PAÍS / MAPA
        if "pais_autor" in df and not df["pais_autor"].dropna().empty:
            st.markdown("---")
            st.subheader("🗺️ Geografía Literaria")

            # Contar libros por país
            conteo_paises = (
                df["pais_autor"]
                .value_counts()
                .reset_index()
                .rename(columns={"index": "pais", "pais_autor": "cantidad"})
            )

            if "count" in conteo_paises.columns:
                conteo_paises.columns = ["pais", "cantidad"]

            total_paises = conteo_paises["pais"].nunique()

            col_texto, col_mapa = st.columns([1, 2])

            with col_texto:
                st.markdown(
                    f"""
                    ### 🌍 Alcance Global
                    En tu biblioteca podés encontrar **{total_paises} país(es)** representados.

                    *Pasa el cursor sobre el mapa para ver cuántos libros tenés de cada lugar.*
                    """
                )

            with col_mapa:
                fig_mapa = px.choropleth(
                    conteo_paises,
                    locationmode="country names",
                    locations="pais",
                    color="cantidad",
                    hover_name="pais",
                    hover_data={"cantidad": True, "pais": False},
                    color_continuous_scale="Magma",
                    title="Distribución de libros por país",
                )
                fig_mapa.update_layout(
                    margin={"r": 0, "t": 40, "l": 0, "b": 0},
                    coloraxis_showscale=False,
                )
                st.plotly_chart(fig_mapa, use_container_width=True)

    # PESTAÑA 3: EXPORTAR
    with tab3:
        st.subheader("Tabla Completa de Datos")
        st.dataframe(df, use_container_width=True)
        csv_data = df.to_csv(index=False).encode("utf-8")
        st.download_button(
            "📥 Descargar Biblioteca como CSV",
            data=csv_data,
            file_name="mi_biblioteca.csv",
            mime="text/csv",
        )